name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@latest
      with:
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@latest
      with:
        args: run python -m pytest --cov=redis_index --cov-branch --cov-fail-under=100 tests/
